chooser=simple
delay=1
timeout=1
default=linux
#
image=vmlinuz-huge
        label=linux-huge
        read-only
        append="root=/dev/nvme0n1p3 vga=normal ro mitigations=off i915.enable_guc=3 i915.enable_fbc=1"

image=vmlinuz-generic
        label=linux-generic
        initrd=initrd-generic.gz
        read-only
        append="root=/dev/nvme0n1p3 vga=normal ro mitigations=off i915.enable_guc=3 i915.enable_fbc=1"

image=vmlinuz
        label=linux
        initrd=initrd.gz
        read-only
        append="root=/dev/nvme0n1p3 vga=normal ro mitigations=off i915.enable_guc=3 i915.enable_fbc=1"
