#!/bin/bash
set -e
MIRROR='http://mirrors.tuna.tsinghua.edu.cn/slackware/slackware64-current'

wget() {
  /usr/bin/wget -qc --show-progress -t 3 --waitretry=3 "$@"
}

fname() {
  grep -F "PACKAGE NAME:  $*" | awk -F'  ' '{print $2}'
}

fpath() {
  grep -FA1 "PACKAGE NAME:  $*" | awk -F'  ' '{print $2}' | tac | sed -z 's|\n|/|'
}

upgrade() {
  local pkg="$(cat PACKAGES.TXT | fname $*)"
  if [ ! -f /var/log/packages/"${pkg%.t*}" ]; then
    wget "$MIRROR/$(cat PACKAGES.TXT | fpath $*)"
    upgradepkg --install-new "$pkg"
    rm -f "$pkg"
  fi
}

cd /tmp

if [ ! -r PACKAGES.TXT ]; then
  wget "$MIRROR"/PACKAGES.TXT
fi

VERSION=$(grep -Eo 'kernel-generic-.*-x86_64' PACKAGES.TXT | head -1 | awk -F- '{print $3}')
echo Upgrading kernel to linux v"$VERSION"...

upgrade kernel-generic
upgrade kernel-headers
upgrade kernel-source
upgrade kernel-firmware

rm -f PACKAGES.TXT

cd - >/dev/null 2>&1
