#!/bin/dash
exec /usr/local/libexec/upgrade-current-packages \
  "Kernel packages are up to date. Reboot if packages were upgraded." \
  kernel-generic \
  kernel-headers \
  kernel-source \
  kernel-firmware
