[Metadata]
Name=Greybird Dark
Version=1
Author=Local
Description=Fcitx5 theme based on Greybird Dark GTK
ScaleWithDPI=True

[InputPanel]
NormalColor=#eeeeec
HighlightCandidateColor=#ffffff
HighlightColor=#ffffff
HighlightBackgroundColor=#145ba6
FullWidthHighlight=False
PageButtonAlignment=Last Candidate

[InputPanel/ContentMargin]
Left=7
Right=7
Top=7
Bottom=7

[InputPanel/TextMargin]
Left=7
Right=7
Top=4
Bottom=4

[InputPanel/ShadowMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/Background]
Image=panel.png
Color=#3b3e3f

[InputPanel/Background/Margin]
Left=9
Right=9
Top=9
Bottom=9

[InputPanel/Highlight]
Image=highlight.png
Color=#145ba6

[InputPanel/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=4
Right=4
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu]
NormalColor=#eeeeec
HighlightCandidateColor=#ffffff
Spacing=1

[Menu/ContentMargin]
Left=7
Right=7
Top=7
Bottom=7

[Menu/TextMargin]
Left=7
Right=7
Top=4
Bottom=4

[Menu/Background]
Image=panel.png
Color=#3b3e3f

[Menu/Background/Margin]
Left=9
Right=9
Top=9
Bottom=9

[Menu/Highlight]
Image=highlight.png
Color=#145ba6

[Menu/Highlight/Margin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Separator]
Color=#222425

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=next.png
